/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/games': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Game Route */
    post: operations['create_game_route_v1_games_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/games/{game_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Game Route */
    get: operations['get_game_route_v1_games__game_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/games/{game_id}/attempts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Attempt Route */
    post: operations['submit_attempt_route_v1_games__game_id__attempts_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/games/{game_id}/abandon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Abandon Game Route */
    post: operations['abandon_game_route_v1_games__game_id__abandon_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daily': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Daily Route */
    get: operations['get_daily_route_v1_daily_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daily/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Daily Route */
    post: operations['start_daily_route_v1_daily_start_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/daily/leaderboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Daily Leaderboard Route */
    get: operations['daily_leaderboard_route_v1_daily_leaderboard_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/challenges/{challenge_id}/results': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Challenge Results Route */
    get: operations['challenge_results_route_v1_challenges__challenge_id__results_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/challenges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Challenge Route */
    post: operations['create_challenge_route_v1_challenges_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/challenges/mine': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Owned Challenges Route */
    get: operations['owned_challenges_route_v1_challenges_mine_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/challenges/{share_code}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Challenge Route */
    get: operations['get_challenge_route_v1_challenges__share_code__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/challenges/{share_code}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Challenge Route */
    post: operations['start_challenge_route_v1_challenges__share_code__start_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/challenges/{challenge_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Challenge Route */
    delete: operations['revoke_challenge_route_v1_challenges__challenge_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rooms/{room_id}/ws-ticket': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Websocket Ticket Route */
    post: operations['create_websocket_ticket_route_v1_rooms__room_id__ws_ticket_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rooms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Room Route */
    post: operations['create_room_route_v1_rooms_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rooms/{room_code}/join': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join Room Route */
    post: operations['join_room_route_v1_rooms__room_code__join_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rooms/{room_id}/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ready Room Route */
    post: operations['ready_room_route_v1_rooms__room_id__ready_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/rooms/{room_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Room Route */
    get: operations['get_room_route_v1_rooms__room_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/leaderboards': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Leaderboard Route */
    get: operations['get_leaderboard_route_v1_leaderboards_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Profile Route */
    get: operations['get_profile_route_v1_me_profile_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Profile Route */
    patch: operations['update_profile_route_v1_me_profile_patch'];
    trace?: never;
  };
  '/v1/me/games': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Games Route */
    get: operations['get_games_route_v1_me_games_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Stats Route */
    get: operations['get_stats_route_v1_me_stats_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export Route */
    get: operations['export_route_v1_me_export_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Account Route */
    delete: operations['delete_account_route_v1_me_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/support': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Support Request Route */
    post: operations['create_support_request_route_v1_support_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/analytics/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Collect Event Route */
    post: operations['collect_event_route_v1_analytics_events_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/games': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Games Route */
    get: operations['games_route_v1_admin_games_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/profiles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Profiles Route */
    get: operations['profiles_route_v1_admin_profiles_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/rooms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rooms Route */
    get: operations['rooms_route_v1_admin_rooms_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/challenges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Challenges Route */
    get: operations['challenges_route_v1_admin_challenges_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/leaderboard-review': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Leaderboard Review Route */
    get: operations['leaderboard_review_route_v1_admin_leaderboard_review_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Summary Route */
    get: operations['summary_route_v1_admin_summary_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/flags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Flags Route */
    get: operations['flags_route_v1_admin_flags_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/flags/{key}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Flag Route */
    patch: operations['update_flag_route_v1_admin_flags__key__patch'];
    trace?: never;
  };
  '/v1/admin/leaderboard/{entry_id}/invalidate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invalidate Leaderboard Route */
    post: operations['invalidate_leaderboard_route_v1_admin_leaderboard__entry_id__invalidate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/leaderboard/{entry_id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore Leaderboard Route */
    post: operations['restore_leaderboard_route_v1_admin_leaderboard__entry_id__restore_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/profiles/{user_id}/moderate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Moderate Profile Route */
    post: operations['moderate_profile_route_v1_admin_profiles__user_id__moderate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/challenges/{challenge_id}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Revoke Challenge Route */
    post: operations['admin_revoke_challenge_route_v1_admin_challenges__challenge_id__revoke_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/rooms/{room_id}/terminate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Terminate Room Route */
    post: operations['terminate_room_route_v1_admin_rooms__room_id__terminate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit Route */
    get: operations['audit_route_v1_admin_audit_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AchievementProgressSchema */
    AchievementProgressSchema: {
      /** Current */
      current: number;
      /** Target */
      target: number;
    };
    /** AdminActionRequest */
    AdminActionRequest: {
      /** Reason */
      reason: string;
      /** Enabled */
      enabled?: boolean | null;
      /** Displayname */
      displayName?: string | null;
    };
    /** AdminChallengeItem */
    AdminChallengeItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Creatorid
       * Format: uuid
       */
      creatorId: string;
      /** Title */
      title: string | null;
      /** Completedcount */
      completedCount: number;
      /** Revokedat */
      revokedAt: string | null;
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** AdminGameItem */
    AdminGameItem: {
      /** Id */
      id: string;
      /**
       * Ownerid
       * Format: uuid
       */
      ownerId: string;
      /** Mode */
      mode: string;
      /** Status */
      status: string;
      /** Difficulty */
      difficulty: string | null;
      /** Attemptsused */
      attemptsUsed: number;
      /** Maxattempts */
      maxAttempts: number;
      /** Score */
      score: number | null;
      /** Rankedeligibility */
      rankedEligibility: string;
      /**
       * Startedat
       * Format: date-time
       */
      startedAt: string;
      /** Completedat */
      completedAt: string | null;
    };
    /** AdminLeaderboardItem */
    AdminLeaderboardItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Gameid
       * Format: uuid
       */
      gameId: string;
      /**
       * Userid
       * Format: uuid
       */
      userId: string;
      /** Category */
      category: string;
      /** Score */
      score: number;
      /** Attemptsused */
      attemptsUsed: number;
      /** Elapsedseconds */
      elapsedSeconds: number;
      /** Reviewstatus */
      reviewStatus: string;
      /** Invalidatedat */
      invalidatedAt: string | null;
      /**
       * Completedat
       * Format: date-time
       */
      completedAt: string;
    };
    /** AdminPage[AdminChallengeItem] */
    AdminPage_AdminChallengeItem_: {
      /** Items */
      items: components['schemas']['AdminChallengeItem'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
    };
    /** AdminPage[AdminGameItem] */
    AdminPage_AdminGameItem_: {
      /** Items */
      items: components['schemas']['AdminGameItem'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
    };
    /** AdminPage[AdminLeaderboardItem] */
    AdminPage_AdminLeaderboardItem_: {
      /** Items */
      items: components['schemas']['AdminLeaderboardItem'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
    };
    /** AdminPage[AdminProfileItem] */
    AdminPage_AdminProfileItem_: {
      /** Items */
      items: components['schemas']['AdminProfileItem'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
    };
    /** AdminPage[AdminRoomItem] */
    AdminPage_AdminRoomItem_: {
      /** Items */
      items: components['schemas']['AdminRoomItem'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
    };
    /** AdminProfileItem */
    AdminProfileItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Displayname */
      displayName: string | null;
      /** Isanonymous */
      isAnonymous: boolean;
      /** Publicleaderboards */
      publicLeaderboards: boolean;
      /** Isbanned */
      isBanned: boolean;
      /** Deletedat */
      deletedAt: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** AdminRoomItem */
    AdminRoomItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
      /** Membercount */
      memberCount: number;
      /** Winnerid */
      winnerId: string | null;
      /** Istie */
      isTie: boolean;
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** AdminSummary */
    AdminSummary: {
      /** Profiles */
      profiles: number;
      /** Activegames */
      activeGames: number;
      /** Completedgames */
      completedGames: number;
      /** Activerooms */
      activeRooms: number;
      /** Pendingreviewentries */
      pendingReviewEntries: number;
    };
    /** AnalyticsEventRequest */
    AnalyticsEventRequest: {
      /**
       * Clienteventid
       * Format: uuid
       */
      clientEventId: string;
      /**
       * Eventname
       * @enum {string}
       */
      eventName:
        | 'game_started'
        | 'game_completed'
        | 'game_abandoned'
        | 'difficulty_selected'
        | 'daily_completed'
        | 'friend_challenge_created'
        | 'room_joined'
        | 'duel_completed'
        | 'validation_error'
        | 'reconnect'
        | 'account_upgraded';
      /**
       * Consent
       * @constant
       */
      consent: true;
      /**
       * Consentversion
       * @constant
       */
      consentVersion: 'privacy-v1';
      /**
       * Locale
       * @enum {string}
       */
      locale: 'en' | 'zh-Hant';
      /** Mode */
      mode?: ('solo' | 'daily' | 'practice' | 'pass_and_play' | 'friend_challenge' | 'duel') | null;
      /** Difficulty */
      difficulty?: ('easy' | 'normal' | 'hard' | 'expert' | 'custom') | null;
      /** Result */
      result?: ('won' | 'lost' | 'abandoned' | 'expired' | 'tie') | null;
      /** Attemptsused */
      attemptsUsed?: number | null;
      /** Ranked */
      ranked?: boolean | null;
      /** Scoreband */
      scoreBand?: ('zero' | '1-999' | '1000-1499' | '1500+') | null;
      /** Dailychallengeid */
      dailyChallengeId?: string | null;
      /** Official */
      official?: boolean | null;
      /** Expiryband */
      expiryBand?: '30_days' | null;
      /** Roomstate */
      roomState?: ('waiting' | 'active' | 'completed' | 'expired' | 'terminated') | null;
      /** Reconnect */
      reconnect?: boolean | null;
      /** Tie */
      tie?: boolean | null;
      /** Validationcategory */
      validationCategory?:
        ('game_config' | 'guess' | 'challenge' | 'room' | 'profile' | 'auth') | null;
      /** Surface */
      surface?: ('game' | 'room' | 'daily' | 'challenge' | 'account') | null;
      /** Recovered */
      recovered?: boolean | null;
      /** Previousanonymous */
      previousAnonymous?: boolean | null;
    };
    /** AnalyticsEventResponse */
    AnalyticsEventResponse: {
      /** Received */
      received: boolean;
    };
    /** AttemptRequest */
    AttemptRequest: {
      /** Guess */
      guess: string[];
      /** Idempotencykey */
      idempotencyKey: string;
    };
    /** AttemptSchema */
    AttemptSchema: {
      /** Number */
      number: number;
      /** Guess */
      guess: string[];
      feedback: components['schemas']['FeedbackSchema'];
      /**
       * Submittedat
       * Format: date-time
       */
      submittedAt: string;
    };
    /** AuditEventResponse */
    AuditEventResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Actorid */
      actorId: string | null;
      /** Action */
      action: string;
      /** Targettype */
      targetType: string;
      /** Targetid */
      targetId: string;
      /** Reason */
      reason: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** ChallengeResponse */
    ChallengeResponse: {
      /** Id */
      id?: string | null;
      /** Sharecode */
      shareCode: string;
      /** Title */
      title: string | null;
      /** Creatorname */
      creatorName: string | null;
      config: components['schemas']['GameConfigSchema'];
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string;
      /** Revoked */
      revoked: boolean;
      /**
       * Completedcount
       * @default 0
       */
      completedCount: number;
    };
    /** ChallengeResultItem */
    ChallengeResultItem: {
      /** Rank */
      rank: number;
      /** Playerlabel */
      playerLabel: string;
      /** Result */
      result: string;
      /** Attemptsused */
      attemptsUsed: number;
      /** Maxattempts */
      maxAttempts: number;
      /** Score */
      score: number;
      /** Elapsedseconds */
      elapsedSeconds: number | null;
      /**
       * Completedat
       * Format: date-time
       */
      completedAt: string;
    };
    /** ChallengeResultsResponse */
    ChallengeResultsResponse: {
      /** Completedcount */
      completedCount: number;
      /** Winrate */
      winRate: number;
      /** Averageattempts */
      averageAttempts: number | null;
      /** Scoredistribution */
      scoreDistribution: {
        [key: string]: number;
      };
      /** Items */
      items: components['schemas']['ChallengeResultItem'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
    };
    /**
     * CodeMakerType
     * @enum {string}
     */
    CodeMakerType: 'computer' | 'human';
    /** CreateChallengeRequest */
    CreateChallengeRequest: {
      /** Difficulty */
      difficulty?: ('easy' | 'normal' | 'hard' | 'expert') | null;
      config?: components['schemas']['GameConfigSchema'] | null;
      /** Secret */
      secret?: string[] | null;
      /** Title */
      title?: string | null;
      /**
       * Showcreatorname
       * @default true
       */
      showCreatorName: boolean;
      /** Idempotencykey */
      idempotencyKey?: string | null;
    };
    /** CreateGameRequest */
    CreateGameRequest: {
      /** @default solo */
      mode: components['schemas']['GameMode'];
      /** Difficulty */
      difficulty?: ('easy' | 'normal' | 'hard' | 'expert') | null;
      config?: components['schemas']['GameConfigSchema'] | null;
      /** Secret */
      secret?: string[] | null;
      /** Idempotencykey */
      idempotencyKey?: string | null;
    };
    /** CreateRoomRequest */
    CreateRoomRequest: {
      /**
       * Difficulty
       * @default normal
       * @enum {string}
       */
      difficulty: 'easy' | 'normal' | 'hard' | 'expert';
      /** Idempotencykey */
      idempotencyKey?: string | null;
    };
    /** DailyDefinitionResponse */
    DailyDefinitionResponse: {
      /** Id */
      id: string;
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Rulesetversion */
      ruleSetVersion: string;
      /** Derivationversion */
      derivationVersion: string;
      config: components['schemas']['GameConfigSchema'];
      /**
       * Rolloverat
       * Format: date-time
       */
      rolloverAt: string;
    };
    /** DeleteAccountRequest */
    DeleteAccountRequest: {
      /**
       * Confirmation
       * @constant
       */
      confirmation: 'DELETE';
    };
    /** DeleteAccountResponse */
    DeleteAccountResponse: {
      /** Deleted */
      deleted: boolean;
    };
    /** FeatureFlagResponse */
    FeatureFlagResponse: {
      /** Key */
      key: string;
      /** Enabled */
      enabled: boolean;
    };
    /** FeedbackSchema */
    FeedbackSchema: {
      /** Black */
      black: number;
      /** White */
      white: number;
    };
    /** GameConfigSchema */
    GameConfigSchema: {
      /** Colours */
      colours: string[];
      /** Codelength */
      codeLength: number;
      /** Maxattempts */
      maxAttempts: number;
      /** Duplicatesallowed */
      duplicatesAllowed: boolean;
      /** @default computer */
      codeMaker: components['schemas']['CodeMakerType'];
      /** @default private */
      visibility: components['schemas']['GameVisibility'];
      /**
       * Ranked
       * @default false
       */
      ranked: boolean;
      /**
       * Timebonuscap
       * @default 300
       */
      timeBonusCap: number;
    };
    /**
     * GameMode
     * @enum {string}
     */
    GameMode: 'solo' | 'daily' | 'practice' | 'pass_and_play' | 'friend_challenge' | 'duel';
    /** GameResponse */
    GameResponse: {
      /** Id */
      id: string;
      /** Mode */
      mode: string;
      /** Status */
      status: string;
      /** Difficulty */
      difficulty: string | null;
      config: components['schemas']['GameConfigSchema'];
      /** Attempts */
      attempts: components['schemas']['AttemptSchema'][];
      /** Attemptsused */
      attemptsUsed: number;
      /** Maxattempts */
      maxAttempts: number;
      /** Attemptsremaining */
      attemptsRemaining: number;
      /**
       * Startedat
       * Format: date-time
       */
      startedAt: string;
      /** Completedat */
      completedAt: string | null;
      /** Score */
      score: number | null;
      scoreBreakdown: components['schemas']['ScoreBreakdownSchema'] | null;
      /** Secret */
      secret?: string[] | null;
      /** Ranked */
      ranked: boolean;
    };
    /**
     * GameVisibility
     * @enum {string}
     */
    GameVisibility: 'private' | 'shareable' | 'public';
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LeaderboardItem */
    LeaderboardItem: {
      /** Rank */
      rank: number;
      /** Displayname */
      displayName: string;
      /** Score */
      score: number;
      /** Attemptsused */
      attemptsUsed: number;
      /** Elapsedseconds */
      elapsedSeconds: number;
      /**
       * Completedat
       * Format: date-time
       */
      completedAt: string;
      /** Iscurrentuser */
      isCurrentUser: boolean;
    };
    /** OwnedChallengeItem */
    OwnedChallengeItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string | null;
      /** Showcreatorname */
      showCreatorName: boolean;
      config: components['schemas']['GameConfigSchema'];
      /** Revoked */
      revoked: boolean;
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string;
      /** Completedcount */
      completedCount: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** PaginatedGames */
    PaginatedGames: {
      /** Items */
      items: components['schemas']['GameResponse'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
    };
    /** PaginatedLeaderboard */
    PaginatedLeaderboard: {
      /** Items */
      items: components['schemas']['LeaderboardItem'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
      /** Currentuserrank */
      currentUserRank: number | null;
    };
    /** PaginatedOwnedChallenges */
    PaginatedOwnedChallenges: {
      /** Items */
      items: components['schemas']['OwnedChallengeItem'][];
      /** Page */
      page: number;
      /** Pagesize */
      pageSize: number;
      /** Total */
      total: number;
    };
    /** ProfileResponse */
    ProfileResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Displayname */
      displayName: string | null;
      /** Isanonymous */
      isAnonymous: boolean;
      /** Publicleaderboards */
      publicLeaderboards: boolean;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string;
    };
    /** ProfileUpdateRequest */
    ProfileUpdateRequest: {
      /** Displayname */
      displayName?: string | null;
      /** Publicleaderboards */
      publicLeaderboards?: boolean | null;
    };
    /** RoomMemberResponse */
    RoomMemberResponse: {
      /**
       * Userid
       * Format: uuid
       */
      userId: string;
      /** Displayname */
      displayName: string;
      /** Connected */
      connected: boolean;
      /** Ready */
      ready: boolean;
      /** Readyat */
      readyAt: string | null;
      /** Attemptsused */
      attemptsUsed: number;
      /** Completed */
      completed: boolean;
      /** Gameid */
      gameId: string | null;
    };
    /** RoomResponse */
    RoomResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Roomcode */
      roomCode?: string | null;
      /** Status */
      status: string;
      config: components['schemas']['GameConfigSchema'];
      /** Members */
      members: components['schemas']['RoomMemberResponse'][];
      /** Winnerid */
      winnerId: string | null;
      /** Istie */
      isTie: boolean;
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string;
      /** Eventsequence */
      eventSequence: number;
    };
    /** ScoreBreakdownSchema */
    ScoreBreakdownSchema: {
      /** Attempts */
      attempts: number;
      /** Difficulty */
      difficulty: number;
      /** Time */
      time: number;
      /** Total */
      total: number;
      /** Version */
      version: string;
    };
    /** StartGameRequest */
    StartGameRequest: {
      /**
       * Practice
       * @default false
       */
      practice: boolean;
    };
    /** StatsResponse */
    StatsResponse: {
      /** Gamesplayed */
      gamesPlayed: number;
      /** Gameswon */
      gamesWon: number;
      /** Gameslost */
      gamesLost: number;
      /** Gamesabandoned */
      gamesAbandoned: number;
      /** Winrate */
      winRate: number;
      /** Averageattemptsonwins */
      averageAttemptsOnWins: number | null;
      /** Bestscorebydifficulty */
      bestScoreByDifficulty: {
        [key: string]: number;
      };
      /** Dailystreak */
      dailyStreak: number;
      /** Dailycompletionhistory */
      dailyCompletionHistory: string[];
      /** Fastesteligiblesolve */
      fastestEligibleSolve: number | null;
      /** Totalblackpegs */
      totalBlackPegs: number;
      /** Totalwhitepegs */
      totalWhitePegs: number;
      /** Favouritemode */
      favouriteMode: string | null;
      /** Achievements */
      achievements: string[];
      /** Achievementprogress */
      achievementProgress: {
        [key: string]: components['schemas']['AchievementProgressSchema'];
      };
    };
    /** SupportRequestCreate */
    SupportRequestCreate: {
      /**
       * Topic
       * @enum {string}
       */
      topic: 'account' | 'gameplay' | 'accessibility' | 'privacy' | 'safety' | 'other';
      /** Replyemail */
      replyEmail: string;
      /** Message */
      message: string;
    };
    /** SupportRequestResponse */
    SupportRequestResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Received */
      received: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WebSocketTicketResponse */
    WebSocketTicketResponse: {
      /** Ticket */
      ticket: string;
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create_game_route_v1_games_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGameRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_game_route_v1_games__game_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  submit_attempt_route_v1_games__game_id__attempts_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AttemptRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  abandon_game_route_v1_games__game_id__abandon_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_daily_route_v1_daily_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DailyDefinitionResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_daily_route_v1_daily_start_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['StartGameRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  daily_leaderboard_route_v1_daily_leaderboard_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedLeaderboard'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  challenge_results_route_v1_challenges__challenge_id__results_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        challenge_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChallengeResultsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_challenge_route_v1_challenges_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateChallengeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChallengeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  owned_challenges_route_v1_challenges_mine_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedOwnedChallenges'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_challenge_route_v1_challenges__share_code__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        share_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChallengeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_challenge_route_v1_challenges__share_code__start_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        share_code: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['StartGameRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  revoke_challenge_route_v1_challenges__challenge_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        challenge_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_websocket_ticket_route_v1_rooms__room_id__ws_ticket_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        room_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WebSocketTicketResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_room_route_v1_rooms_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRoomRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  join_room_route_v1_rooms__room_code__join_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        room_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  ready_room_route_v1_rooms__room_id__ready_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        room_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_room_route_v1_rooms__room_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        room_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RoomResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_leaderboard_route_v1_leaderboards_get: {
    parameters: {
      query?: {
        period?: string;
        difficulty?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedLeaderboard'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_profile_route_v1_me_profile_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_profile_route_v1_me_profile_patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileUpdateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfileResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_games_route_v1_me_games_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedGames'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_stats_route_v1_me_stats_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  export_route_v1_me_export_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_account_route_v1_me_delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeleteAccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_support_request_route_v1_support_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SupportRequestCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupportRequestResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  collect_event_route_v1_analytics_events_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AnalyticsEventRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AnalyticsEventResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  games_route_v1_admin_games_get: {
    parameters: {
      query?: {
        status?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminPage_AdminGameItem_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  profiles_route_v1_admin_profiles_get: {
    parameters: {
      query?: {
        moderation_only?: boolean;
        search?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminPage_AdminProfileItem_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rooms_route_v1_admin_rooms_get: {
    parameters: {
      query?: {
        active_only?: boolean;
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminPage_AdminRoomItem_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  challenges_route_v1_admin_challenges_get: {
    parameters: {
      query?: {
        active_only?: boolean;
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminPage_AdminChallengeItem_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  leaderboard_review_route_v1_admin_leaderboard_review_get: {
    parameters: {
      query?: {
        status?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminPage_AdminLeaderboardItem_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  summary_route_v1_admin_summary_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSummary'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  flags_route_v1_admin_flags_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeatureFlagResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_flag_route_v1_admin_flags__key__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminActionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FeatureFlagResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  invalidate_leaderboard_route_v1_admin_leaderboard__entry_id__invalidate_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminActionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: boolean;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  restore_leaderboard_route_v1_admin_leaderboard__entry_id__restore_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        entry_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminActionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: boolean;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  moderate_profile_route_v1_admin_profiles__user_id__moderate_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminActionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: boolean;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  admin_revoke_challenge_route_v1_admin_challenges__challenge_id__revoke_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        challenge_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminActionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: boolean;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  terminate_room_route_v1_admin_rooms__room_id__terminate_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        room_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminActionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: boolean;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  audit_route_v1_admin_audit_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditEventResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
